// Copyright 2020 The xgen Authors. All rights reserved.
//
// DO NOT EDIT: generated by xgen XSD generator
//
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

package schema

import (
	"time"
)

type MyType1 []byte

type MyType2 struct {
	LengthAttr int `xml:"length,attr,omitempty"`
}

type MyType3 struct {
	LengthAttr int `xml:"length,attr,omitempty"`
}

type MyType4 struct {
	Title     string    `xml:"title"`
	Blob      []byte    `xml:"blob"`
	Timestamp time.Time `xml:"timestamp"`
}

type MyType5 time.Time
