// Code generated by xgen. DO NOT EDIT.

package schema

// ListType ...
type ListType []string

// UnionType ...
type UnionType struct {
	Int    *int
	String *string
}

// BasicType ...
type BasicType string

// ComplexTypeTest ...
type ComplexTypeTest struct {
	Field1    string  `xml:"field1"`
	Field2    *int    `xml:"field2"`
	Attr1Attr *string `xml:"attr1,attr"`
}

// TestGroup ...
type TestGroup struct {
	GroupField1 string `xml:"groupField1"`
	GroupField2 *int   `xml:"groupField2"`
}

// TestAttributeGroup ...
type TestAttributeGroup struct {
	AttrGroupField1Attr *string `xml:"attrGroupField1,attr"`
	AttrGroupField2Attr *int    `xml:"attrGroupField2,attr"`
}

// TestElement ...
type TestElement	string

