// Code generated by xgen. DO NOT EDIT.

// MyType1 ...
typedef char MyType1[];

// MyType2 ...
typedef struct {
	int LengthAttr; // attr, optional
} MyType2;

// MyType3 ...
typedef struct {
	int LengthAttr; // attr, optional
} MyType3;

// MyType4 ...
typedef struct {
	char Title;
	char Blob[];
	char Timestamp;
} MyType4;

// MyType5 ...
typedef char MyType5;
